import { BibleBookShortform } from '@/lib/types';

export const bibleBooksShortForms: BibleBookShortform[] = [
  {
    name: 'genesis',
    abbreviations: ['gen', 'ge', 'gn'],
  },
  {
    name: 'exodus',
    abbreviations: ['ex', 'exod', 'exo'],
  },
  {
    name: 'exodus',
    abbreviations: ['ex', 'exod', 'exo'],
  },
  {
    name: 'leviticus',
    abbreviations: ['lev', 'le', 'lv'],
  },
  {
    name: 'numbers',
    abbreviations: ['num', 'nu', 'nm', 'nb'],
  },
  {
    name: 'deuteronomy',
    abbreviations: ['deut', 'de', 'dt'],
  },
  {
    name: 'joshua',
    abbreviations: ['josh', 'jos', 'jsh'],
  },
  {
    name: 'judges',
    abbreviations: ['judg', 'jg', 'jdgs'],
  },
  {
    name: 'ruth',
    abbreviations: ['rth', 'ru'],
  },
  {
    name: '1 samuel',
    abbreviations: [
      '1 sam',
      '1 sa',
      '1 s',
      'i sam',
      'i sa',
      '1sa',
      '1s',
      '1st samuel',
      '1st sam',
      'first samuel',
      'first sam',
    ],
  },
  {
    name: '2 samuel',
    abbreviations: [
      '2 sam',
      '2 sa',
      '2 s',
      'ii sam',
      'ii sa',
      '2sa',
      '2s',
      '2nd samuel',
      '2nd sam',
      'second samuel',
      'second sam',
    ],
  },
  {
    name: '1 kings',
    abbreviations: [
      '1 kgs',
      '1 ki',
      '1kgs',
      '1kin',
      '1ki',
      '1k',
      'i kgs',
      'i ki',
      '1st kings',
      '1st kgs',
      'first kings',
      'first kgs',
    ],
  },
  {
    name: '2 kings',
    abbreviations: [
      '2 kgs',
      '2 ki',
      '2kgs',
      '2kin',
      '2ki',
      '2k',
      'ii kgs',
      'ii ki',
      '2nd kings',
      '2nd kgs',
      'second kings',
      'second kgs',
    ],
  },
  {
    name: '1 chronicles',
    abbreviations: [
      '1 chr',
      '1 ch',
      '1chron',
      '1chr',
      '1ch',
      'i chron',
      'i chr',
      'i ch',
      '1st chronicles',
      '1st chron',
      'first chronicles',
      'first chron',
    ],
  },
  {
    name: '2 chronicles',
    abbreviations: [
      '2 chr',
      '2 ch',
      '2chron',
      '2chr',
      '2ch',
      'ii chron',
      'ii chr',
      'ii ch',
      '2nd chronicles',
      '2nd chron',
      'second chronicles',
      'second chron',
    ],
  },
  {
    name: 'ezra',
    abbreviations: ['ezr', 'ez'],
  },
  {
    name: 'nehemiah',
    abbreviations: ['neh', 'ne'],
  },
  {
    name: 'esther',
    abbreviations: ['est', 'esth', 'es'],
  },
  {
    name: 'job',
    abbreviations: ['jb'],
  },
  {
    name: 'psalms',
    abbreviations: ['ps', 'psalm', 'pslm', 'psa', 'psm', 'pss'],
  },
  { name: 'proverbs', abbreviations: ['prov', 'pro', 'prv', 'pr'] },
  {
    name: 'ecclesiastes',
    abbreviations: ['eccles', 'eccle', 'ecc', 'ec', 'qoh'],
  },
  {
    name: 'song of solomon',
    abbreviations: [
      'song',
      'song of songs',
      'sos',
      'so',
      'canticle of canticles',
      'canticle',
      'cant',
    ],
  },
  { name: 'isaiah', abbreviations: ['isa', 'is'] },
  { name: 'jeremiah', abbreviations: ['jer', 'je', 'jr'] },
  { name: 'lamentations', abbreviations: ['lam', 'la'] },
  { name: 'ezekiel', abbreviations: ['ezek', 'eze', 'ezk'] },
  { name: 'daniel', abbreviations: ['dan', 'da', 'dn'] },
  { name: 'hosea', abbreviations: ['hos', 'ho'] },
  { name: 'joel', abbreviations: ['jl'] },
  { name: 'amos', abbreviations: ['am'] },
  { name: 'obadiah', abbreviations: ['obad', 'ob', 'obd'] },
  { name: 'jonah', abbreviations: ['jnh', 'jon'] },
  { name: 'micah', abbreviations: ['mic', 'mc'] },
  { name: 'nahum', abbreviations: ['nah', 'na'] },
  { name: 'habakkuk', abbreviations: ['hab', 'hb'] },
  { name: 'zephaniah', abbreviations: ['zeph', 'zep', 'zp'] },
  { name: 'haggai', abbreviations: ['hag', 'hg'] },
  { name: 'zechariah', abbreviations: ['zech', 'zec', 'zc'] },
  { name: 'malachi', abbreviations: ['mal', 'ml'] },
  { name: 'matthew', abbreviations: ['mat', 'matt', 'mt'] },
  { name: 'mark', abbreviations: ['mrk', 'mar', 'mk', 'mr'] },
  { name: 'luke', abbreviations: ['luk', 'lk'] },
  { name: 'john', abbreviations: ['joh', 'jhn', 'jn'] },
  { name: 'acts', abbreviations: ['act', 'ac'] },
  { name: 'romans', abbreviations: ['rom', 'ro', 'rm'] },
  {
    name: '1 corinthians',
    abbreviations: [
      '1 cor',
      '1 co',
      'i cor',
      'i co',
      '1cor',
      '1co',
      'i corinthians',
      '1corinthians',
      '1st corinthians',
      'first corinthians',
    ],
  },
  {
    name: '2 corinthians',
    abbreviations: [
      '2 cor',
      '2 co',
      'ii cor',
      'ii co',
      '2cor',
      '2co',
      'ii corinthians',
      '2corinthians',
      '2nd corinthians',
      'second corinthians',
    ],
  },
  { name: 'galatians', abbreviations: ['gal', 'ga'] },
  { name: 'ephesians', abbreviations: ['eph', 'ephes'] },
  { name: 'philippians', abbreviations: ['phil', 'php', 'pp'] },
  { name: 'colossians', abbreviations: ['col', 'co'] },
  {
    name: '1 thessalonians',
    abbreviations: [
      '1 thess',
      '1 thes',
      '1 th',
      'i thessalonians',
      'i thess',
      'i thes',
      'i th',
      '1thessalonians',
      '1thess',
      '1thes',
      '1th',
      '1st thessalonians',
      '1st thess',
      'first thessalonians',
      'first thess',
    ],
  },
  {
    name: '2 thessalonians',
    abbreviations: [
      '2 thess',
      '2 thes',
      '2 th',
      'ii thessalonians',
      'ii thess',
      'ii thes',
      'ii th',
      '2thessalonians',
      '2thess',
      '2thes',
      '2th',
      '2nd thessalonians',
      '2nd thess',
      'second thessalonians',
      'second thess',
    ],
  },
  {
    name: '1 timothy',
    abbreviations: [
      '1 tim',
      'i timothy',
      'i tim',
      'i ti',
      '1timothy',
      '1tim',
      '1ti',
      '1st timothy',
      '1st tim',
      'first timothy',
      'first tim',
    ],
  },
  {
    name: '2 timothy',
    abbreviations: [
      '2 tim',
      'ii timothy',
      'ii tim',
      'ii ti',
      '2timothy',
      '2tim',
      '2ti',
      '2nd timothy',
      '2nd tim',
      'second timothy',
      'second tim',
    ],
  },
  { name: 'titus', abbreviations: ['tit', 'ti'] },
  { name: 'philemon', abbreviations: ['philem', 'phm', 'pm'] },
  { name: 'hebrews', abbreviations: ['heb'] },
  { name: 'james', abbreviations: ['jas', 'jm'] },
  {
    name: '1 peter',
    abbreviations: [
      '1 pet',
      '1 pe',
      '1 pt',
      '1 p',
      'i pet',
      'i pt',
      'i pe',
      '1peter',
      '1pe',
      '1pt',
      '1p',
      'i peter',
      '1st peter',
      'first peter',
    ],
  },
  {
    name: '2 peter',
    abbreviations: [
      '2 pet',
      '2 pe',
      '2 pt',
      '2 p',
      'ii pet',
      'ii pt',
      'ii pe',
      '2peter',
      '2pe',
      '2pt',
      '2p',
      'ii peter',
      '2nd peter',
      'second peter',
    ],
  },
  {
    name: '1 john',
    abbreviations: [
      '1 jhn',
      '1 jn',
      '1 j',
      '1john',
      '1jhn',
      '1joh',
      '1jn',
      '1jo',
      '1j',
      'i john',
      'i jhn',
      'i joh',
      'i jn',
      'i jo',
      '1st john',
      'first john',
    ],
  },
  {
    name: '2 john',
    abbreviations: [
      '2 jhn',
      '2 jn',
      '2 j',
      '2john',
      '2jhn',
      '2joh',
      '2jn',
      '2jo',
      '2j',
      'ii john',
      'ii jhn',
      'ii joh',
      'ii jn',
      'ii jo',
      '2nd john',
      'second john',
    ],
  },
  {
    name: '3 john',
    abbreviations: [
      '3 jhn',
      '3 jn',
      '3 j',
      '3john',
      '3jhn',
      '3joh',
      '3jn',
      '3jo',
      '3j',
      'iii john',
      'iii jhn',
      'iii joh',
      'iii jn',
      'iii jo',
      '3rd john',
      'third john',
    ],
  },
  { name: 'jude', abbreviations: ['jud', 'jd'] },
  { name: 'revelation', abbreviations: ['rev', 're', 'the revelation'] },
];
